name: Publish a post
description: Publish a new ChemBioAI post
title: "[Publish] "
labels: ["publish"]
body:
  - type: input
    id: title
    attributes:
      label: Post title
      placeholder: Paste the post title
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Pharma
        - AgTech
        - Science Labs
        - Tools & Tips
        - Global AI Trends
        - Learning Resources
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: 1–2 sentences
      placeholder: Paste the summary
    validations:
      required: true

  - type: textarea
    id: body_html
    attributes:
      label: Body HTML
      description: Blog body only (no <html>/<head>/<body>/<style>/<script>)
      placeholder: Paste BODY HTML here
    validations:
      required: true
